### ISSUE TITLE
Mounting options

### ISSUE THREAD

**Issue by mleonhard** [sparkfun/Qwiic_Alphanumeric_Display_Breakout#1]
Hi SparkFun,
I wish to mount the SparkFun Qwiic Alphanumeric Display on a panel, flush.  I searched and could not find the height of the display elements in any of the docs.
1. What size standoffs should I use to mount this flush on a panel?
1. How big are the mounting holes?
1. How about including this information in the docs?
1. Additionally, you could recommend a particular set of standoffs and screws for flush panel mounting.

Thanks!
-Michael

**Comment by makin-stuff** [comment]
Hi @mleonhard. 

Typically, all our documentation can be found on the [SparkFun product page](https://www.sparkfun.com/products/16916). If you navigate to the "Documents" tab and click "Board Dimensions" you will see an image with all kinds of dimensions for this product. 

The four mounting holes on any corner are always meant for 4-40 screws and standoffs. That's the SparkFun standard. The mounting holes in the middle of the board are meant for mounting without the board wings and fit a M2-0.4 x 6 screw. 

Thanks!

**Comment by mleonhard** [comment]
The "Board Dimensions" image shows only the top view, not the side view.  The data sheet is for the LED driver chip on the back.  I need to know the thickness of the display on the front, so I can choose the right standoffs to flush-mount the display.

**Comment by makin-stuff** [comment]
Ok, gotcha. 

For the dimensions of the display itself you want to look at the display datasheet. These live in the "Documents" folder of this repo. Any of the pdfs starting with "JMF". 

These are manufactured in China, so unfortunately the data sheet is partially in Chinese which can make it hard to understand. But page three shows the mechanical dimensions. The units are in mm. Is this what you were looking for?

<img width="956" alt="Screen Shot 2022-01-25 at 11 00 09 AM" src="https://user-images.githubusercontent.com/54557724/151032976-53dba2de-0d58-4d59-8665-ec75654bcdb0.png">

**Comment by mleonhard** [comment]
Thank you! :)

Here is my plan to mount the display, which may be useful to others:

The display is 8mm tall.  8mm x (1 in / 25.4mm) = 0.315in ~= 5/16 in.  So a 3/8in standoff should leave the display slightly inset on the panel.

The mounting will be: screw head, enclosure wall, standoff, display pcb, screw head.  I will use 1/4in screws.  The standoff is 3/8in and two screws are 4/8in, leaving 1/8in (3mm) for the enclosure wall and display PCB.  If this is too much space, then I will need to put a washer on the inner screw.  Sparkfun doesn't sell washers.  I'll get them at a local store.

- [Standoff - Nylon (4-40; 3/8"; 10 pack)](https://www.sparkfun.com/products/10927)
- [Screw - Phillips Head (1/4", 4-40, 10 pack)](https://www.sparkfun.com/products/10453)
